name = "ProbabilisticParameterEstimators"
uuid = "0098cf3f-3e1e-4f11-b01c-dd9dec1b3374"
authors = ["Romeo Valentin <romeov@stanford.edu>"]
version = "0.8.2"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NonlinearSolveBase = "be0214bd-f91f-a760-ac4e-3421ce2b2da0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SimpleNonlinearSolve = "727e6d20-b764-4bd8-a329-72de5adea6c7"

[weakdeps]
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[sources.BlockDiagonals]
rev = "master"
url = "https://github.com/RomeoV/BlockDiagonals.jl"

[extensions]
TuringExt = "Turing"

[compat]
Accessors = "0.1"
BlockDiagonals = "0.1,0.2"
DifferentiationInterface = "0.7"
Distributions = "0.25"
DocStringExtensions = "0.9"
ForwardDiff = "1"
LinearAlgebra = "1"
Logging = "1"
NonlinearSolveBase = "1, 2"
Random = "1"
SciMLBase = "2"
SimpleNonlinearSolve = "2"
Turing = "0.32,0.33,0.34,0.35,0.36,0.37,0.38,0.39"
julia = "1.11"
