name: Documenter
on:
  push:
    branches: [main, master]
    tags: [v*]
  pull_request:

jobs:
  Documenter:
    permissions:
      contents: write
      statuses: write
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: julia-actions/julia-buildpkg@v1  # if package requires Pkg.build()
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
